data:
  dataset: voxceleb2_dev
  rootdir : '/ssd/data/VoxCeleb/vox2_dev_wav/wav'
  dataset_yaml : 'data/VoxCeleb2_DS_2s_clean.yaml'
  file_extention : wav
  sliding_window : False
  window_len : 3.
  window_shift : 1.5
  sample_rate_target : 16000
  sample_rate_source : 48000
  mic1 : True
  mic2 : False
  do_validation : True

  train :
    duration : 2.04
    users : [0,5394]
    batch_size : 64
    shuffle : False
    examples_per_speaker : 2
    samples_per_speaker : 32
    chunk_per_segment : -1
    overlap: 0.0

    
  val :
    users : [0,5394]
    batch_size : 64
    shuffle : False
    chunk_per_segment : 1
    overlap: 0.0

  test :
    duration : 2.04
    users : [5394, 5993]
    batch_size : 1
    shuffle : False

  num_workers : 0
    

model:
  encoder_dir : 'models/fast_aam_93_2s_asp_ss2_noisy.pt'
  dim_neck : 16
  dim_emb : 256
  dim_pre : 512
  freq : 16
  lambda_cd : 0.05
  from_loading : False
  save_model : False


training :
  num_epoch : 1
  epoch_before_cd : 0
  epoch_before_emb : 0
  len_crop : 128
  lr : 0.0001
  savedir : "models/"
  log_step : 100
  use_mean_embs : True

